'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""P:\Tool & Cutter Grinding\Tool Cut"& _ 
            "ter Database.accdb""")>  _
        Public ReadOnly Property Tool_Cutter_DatabaseConnectionString() As String
            Get
                Return CType(Me("Tool_Cutter_DatabaseConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6.00")>  _
        Public Property oneeighth() As Decimal
            Get
                Return CType(Me("oneeighth"),Decimal)
            End Get
            Set
                Me("oneeighth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14.30")>  _
        Public Property threesixteenths() As Decimal
            Get
                Return CType(Me("threesixteenths"),Decimal)
            End Get
            Set
                Me("threesixteenths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11.55")>  _
        Public Property fifteensixtyfourths() As Decimal
            Get
                Return CType(Me("fifteensixtyfourths"),Decimal)
            End Get
            Set
                Me("fifteensixtyfourths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14.18")>  _
        Public Property onefourth() As Decimal
            Get
                Return CType(Me("onefourth"),Decimal)
            End Get
            Set
                Me("onefourth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7.05")>  _
        Public Property fivesixteenths() As Decimal
            Get
                Return CType(Me("fivesixteenths"),Decimal)
            End Get
            Set
                Me("fivesixteenths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24.01")>  _
        Public Property threeeighths() As Decimal
            Get
                Return CType(Me("threeeighths"),Decimal)
            End Get
            Set
                Me("threeeighths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14.75")>  _
        Public Property sevensixteenths() As Decimal
            Get
                Return CType(Me("sevensixteenths"),Decimal)
            End Get
            Set
                Me("sevensixteenths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("37.16")>  _
        Public Property onehalf() As Decimal
            Get
                Return CType(Me("onehalf"),Decimal)
            End Get
            Set
                Me("onehalf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("46.36")>  _
        Public Property fiveeighths() As Decimal
            Get
                Return CType(Me("fiveeighths"),Decimal)
            End Get
            Set
                Me("fiveeighths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("79.35")>  _
        Public Property threefourths() As Decimal
            Get
                Return CType(Me("threefourths"),Decimal)
            End Get
            Set
                Me("threefourths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Toneeighth() As Decimal
            Get
                Return CType(Me("Toneeighth"),Decimal)
            End Get
            Set
                Me("Toneeighth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tthreesixteenths() As Decimal
            Get
                Return CType(Me("Tthreesixteenths"),Decimal)
            End Get
            Set
                Me("Tthreesixteenths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tfifteensixtyfourths() As Decimal
            Get
                Return CType(Me("Tfifteensixtyfourths"),Decimal)
            End Get
            Set
                Me("Tfifteensixtyfourths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tonefourth() As Decimal
            Get
                Return CType(Me("Tonefourth"),Decimal)
            End Get
            Set
                Me("Tonefourth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tfivesixteenths() As Decimal
            Get
                Return CType(Me("Tfivesixteenths"),Decimal)
            End Get
            Set
                Me("Tfivesixteenths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tthreeeighths() As Decimal
            Get
                Return CType(Me("Tthreeeighths"),Decimal)
            End Get
            Set
                Me("Tthreeeighths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tsevensixteenths() As Decimal
            Get
                Return CType(Me("Tsevensixteenths"),Decimal)
            End Get
            Set
                Me("Tsevensixteenths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tonehalf() As Decimal
            Get
                Return CType(Me("Tonehalf"),Decimal)
            End Get
            Set
                Me("Tonehalf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tfiveeighths() As Decimal
            Get
                Return CType(Me("Tfiveeighths"),Decimal)
            End Get
            Set
                Me("Tfiveeighths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Tthreefourths() As Decimal
            Get
                Return CType(Me("Tthreefourths"),Decimal)
            End Get
            Set
                Me("Tthreefourths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SignedOutVal() As Decimal
            Get
                Return CType(Me("SignedOutVal"),Decimal)
            End Get
            Set
                Me("SignedOutVal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property InventoryVal() As Decimal
            Get
                Return CType(Me("InventoryVal"),Decimal)
            End Get
            Set
                Me("InventoryVal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property timerinterval() As Integer
            Get
                Return CType(Me("timerinterval"),Integer)
            End Get
            Set
                Me("timerinterval") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Strite_Inventory_Management.My.MySettings
            Get
                Return Global.Strite_Inventory_Management.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
